In [8]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("第一列：", arr[0])
print("第二行：", arr[:, 1])
print("對角線：", arr[[0, 1, 2], [0, 1, 2]])

第一列： [1 2 3]
第二行： [2 5 8]
對角線： [1 5 9]


In [10]:
mat = np.random.randint(0, 100, size=(4, 4))
mat

array([[27,  1, 36, 49],
       [24, 16, 94, 88],
       [41, 74, 62, 83],
       [14, 51, 49, 95]], dtype=int32)

In [11]:
arr_rand = np.random.rand(3, 3)
arr_rand

array([[0.05505813, 0.40107836, 0.54327564],
       [0.02386741, 0.92363477, 0.79717515],
       [0.18419311, 0.96912888, 0.18841473]])

In [12]:
arr_randn = np.random.randn(3, 3)
arr_randn

array([[ 1.59212475,  0.99147887, -0.50834281],
       [ 1.08498159,  0.0825371 , -1.55586863],
       [ 0.49456915,  1.41706888, -1.4956365 ]])

In [13]:
arr_normal = np.random.normal(0, 10, (3, 3))
arr_normal

array([[ 1.39550729e-03,  5.95457221e+00, -1.26755576e+01],
       [ 1.55369115e+01,  4.17499578e+00,  3.20036002e-01],
       [-9.81815144e-01, -2.61948332e+00,  3.26922199e+00]])

In [14]:
arr_uniform = np.random.uniform(1, 10, (3, 3))
arr_uniform

array([[4.05910268, 8.41852241, 7.75879768],
       [5.51605219, 2.75531243, 8.75219215],
       [2.67564434, 3.35183985, 8.2653165 ]])