In [1]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])
arr + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [2]:
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
a = np.array([[1],[2],[3]])  # (3,1)
b = np.array([[10, 20, 30]]) # (1,3)

a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [ ]:
# 試作：無法對齊的錯誤訊息
arr + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 