In [4]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print("axis = 0", np.sum(arr, axis = 0))
print("axis = 1", np.sum(arr, axis = 1))

axis = 0 [12 15 18]
axis = 1 [ 6 15 24]


In [6]:
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

[7 8 9]
[3 6 9]
[4. 5. 6.]
[2. 5. 8.]


In [7]:
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
print(np.sum(x, axis = 0))
print("=================")
print(np.sum(x, axis = 1))
print("=================")
print(np.sum(x, axis = 2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]
