In [4]:
import numpy as np

x = np.random.randint(0, 20, size=10)
x[x > 10]

array([17, 18, 16, 11, 18, 14, 12], dtype=int32)

In [5]:
x[x % 3 == 0]

array([18, 18, 12], dtype=int32)

In [7]:
x[(x >= 5) & (x < 15)]

array([ 7,  7, 11, 14, 12], dtype=int32)

In [8]:
mat = np.arange(1, 17).reshape(4, 4)
mat[mat % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [12]:
print(mat)
row_max = np.max(mat, axis = 1)
print("row_max：", mat[mat == row_max[:,None]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row_max： [ 4  8 12 16]
