In [1]:
import numpy as np

In [2]:
x = np.array([5, 12, 3, 20, 10, 6])
np.where(x > 10 , 999, -1)

array([ -1, 999,  -1, 999,  -1,  -1])

In [4]:
print(np.argmax(x))
print(np.argmin(x))

3
2


In [7]:
print(np.sort(x))
print("===============")
print(np.argsort(x))
print("===============")
print(np.argsort(x)[-5:])

[ 3  5  6 10 12 20]
[2 0 5 4 1 3]
[0 5 4 1 3]


In [10]:
y = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

print(np.unique(y))
print(np.unique(y, return_counts = True))

[1 2 3 4]
(array([1, 2, 3, 4]), array([1, 2, 3, 4]))


In [ ]:
print(np.bincount(y))

[0 1 2 3 4]


In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack([a, b]))
print("===============")
print(np.hstack([a, b]))
print("===============")
print(np.vstack([a, b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
